version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-type: development
    ignore-scripts: true

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
